# -*- python -*-

def build(bld):
  bld.program(
    source       = 'graph.cc layout.cc common.cc display.cc interaction.cc main.cc',
    target       = '../graph3d',
    uselib       = 'libs',
    includes     = '.')
